# Generated by Django 6.0.1 on 2026-09-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSEEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='global', max_length=128)),
                ('event_type', models.CharField(default='message', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatsigFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('stage', 'Stage'), ('dev', 'Development')], default='stage', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('checksum', models.CharField(default='', max_length=256)),
            ],
            options={
                'unique_together': {('environment', 'checksum')},
            },
        ),
        migrations.CreateModel(
            name='ProductStatsigSnapShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(default='gpu_100', max_length=100)),
                ('productName', models.CharField(default='gpu model 100 speed 5x memory 5g', max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('featureflaglastchecksum', models.CharField(default='', max_length=256)),
                ('statsig_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.statsigfeatures')),
            ],
            options={
                'indexes': [models.Index(fields=['featureflaglastchecksum'], name='core_produc_feature_f77f6c_idx'), models.Index(fields=['productid', 'timestamp'], name='core_produc_product_2474d9_idx')],
            },
        ),
    ]
