# Generated by Django 6.0.7 on 2026-07-29 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sseevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsigapplication',
            name='data',
        ),
        migrations.AddField(
            model_name='statsigapplication',
            name='environment',
            field=models.CharField(choices=[('prod', 'Production'), ('stage', 'Stage'), ('dev', 'Development')], default='stage', max_length=10),
        ),
        migrations.AddField(
            model_name='statsigapplication',
            name='last_checksum',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='statsigapplication',
            name='product',
            field=models.CharField(default='stage', max_length=100),
        ),
        migrations.CreateModel(
            name='StatsigMetadataSnapShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField()),
                ('statsig_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.statsigapplication')),
            ],
        ),
    ]
